#!/bin/sh

# Get source dir of script. <https://stackoverflow.com/a/29835459/7391331>.
script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

usage() {
    cat << EOF
Add or update Trallnags 'logging' shell library.

This script will ensure that 'log.sh' can be found in the same
directory as this script itself.

Usage:
    $0 [reference]

Options:
    reference: Git reference to checkout. For example a tag. If this
               is not set, the latest commit on the default branch
               will be checked out and used.
    -h, --help: Print this help message.

Examples:
    $0 v1.2.3
EOF
}

case $1 in -h | --help) usage && exit ;; esac



if [ -z "$1" ]; then
    reference=master
else
    reference="$1"
fi

set -eu

dir=git-trallnag-logsh

cd /tmp

if ! [ -d "$dir/.git" ]; then
    echo "Clone 'https://github.com/trallnag/logsh.git' to '$dir'..."
    git clone https://github.com/trallnag/logsh.git "$dir"
    cd "$dir"
else
    echo "Pull 'https://github.com/trallnag/logsh.git' at '$dir'..."
    cd "$dir"
    git pull --all --tags
fi

git checkout "$reference"

echo "Force copy '$dir/log.sh' to '$script_dir/'..."
cp --force log.sh "$script_dir/logsh"
